# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 04:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171029_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
