/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_opencv_opencvcamera_OpencvClass */

#ifndef _Included_com_example_opencv_opencvcamera_OpencvClass
#define _Included_com_example_opencv_opencvcamera_OpencvClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_opencv_opencvcamera_OpencvClass
 * Method:    faceDetection
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_opencv_opencvcamera_OpencvClass_faceDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
